### ISSUE TITLE
Scope "gem-auth" is missing

### ISSUE THREAD

**Issue by simse07** [gematik/ref-idp-server#7]
Hi,

please add all supported scopes of the reference environment:
```
"scopes_supported": [
    "openid",
    "e-rezept",
    "e-rezept-dev",
    "fh-fokus-demis",
    "fhir-vzd",
    "gem-auth",
    "pairing",
    "rpdoc-emma",
    "zvr-bnotk"
  ]
```

Thank you

**Comment by RStaeber** [comment]
Since version [21.0.20](https://github.com/gematik/ref-idp-server/releases/tag/21.0.20) scopes can be configured in [application.yml](https://github.com/gematik/ref-idp-server/blob/master/idp-server/src/main/resources/application.yml) (inside is a [template](https://github.com/gematik/ref-idp-server/blob/3413aae555552823a9b61d358d5f2632dcfa8d97/idp-server/src/main/resources/application.yml#L45) in addition to known scopes).
